---
title: "Project_step_05: Communication"
author: "Lin Wang"
format: pdf
---

## Assessment

1. Reflect on the process of communicating research.

- What did you learn?

Through this process, I learned the importance of tailoring communication to different audiences and the significance of clear and concise messaging. Developing a presentation forced me to distill complex ideas into digestible points and helped me understand my research from a different perspective.

- What did you find most/ least challenging?

The most challenging aspect was condensing my research plan into a presentation while maintaining clarity and coherence while my research were not totally done yet. Balancing depth of content with brevity was difficult, especially when trying to convey the significance and complexity of my research within a limited time frame.

- What resources did you consult?

I consulted various resources, especially our textbook and recipes, others like relevant academic literature on effective communication strategies, online tutorials on presentation design, and feedback from peers. These resources provided valuable guidance on structuring my final presentations and engaging audiences effectively.

2. Consider how your prospectus turned out.

My prospectus evolved significantly through this process. Incorporating feedback from peers and Dr. Jerid helped me refine my research objectives, clarify my methodology, and strengthen the overall coherence of my plan. The prospectus now better reflects the scope and significance of my research.

- Did your interests evolved?

Yes, my interests evolved as I dig deeper in my research process. Developing a presentation forced me to articulate the significance of my research and consider its broader implications, which deepened my appreciation for the subject matter.

- Did your research questions and objectives evolved?

While my core research questions remained consistent, the way I framed and articulated them evolved. Feedback from peers and director prompted me to refine my objectives, clarify my methodology, and ensure alignment between research questions, data preparation strategy, and analysis plan.

- What factors influenced these changes?

Feedback from peers and directors played a significant role in shaping these changes. Their insights and perspectives challenged me to think critically about my research and consider alternative approaches. Additionally, the process of developing a presentation encouraged me to revisit and refine my research questions and objectives to ensure they were effectively communicated to a broader audience. I do remember at the very beginning of our project step 1, I have gotten feedback from Dr. Jerid that my research question was too broad which is challenging for my later writing. Thus, I have narrowed it down to only focus on code-switching phenomenon.